source 'https://rubygems.org'

# Use fastlane version that depends on same version of xcodeproj gem as cocoapods beta
gem 'fastlane', :git => 'https://github.com/arifken/fastlane.git'

# Beta version of cocoapods that works for our project.
gem 'cocoapods', '1.0.0.beta.5'

gem 'hockeyapp', '0.0.15'
gem 'jira-ruby', '0.1.17'
gem 'trollop', '2.1.2'
gem 'POpen4', '0.1.4'
gem 'rest-client', '1.8.0'